# Development mode overrides
# Server runs on host for hot reload, not in Docker
volumes:
  uiv2_node_modules: null
services:
  server:
    # Disable server container - runs on host instead
    profiles:
      - prod-only
  envoy:
    volumes:
      - ./envoy-dev.yaml:/etc/envoy/envoy.yaml
  uiv2:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ${TYPESTREAM_PROJECT_ROOT:-.}/uiv2:/app
      - uiv2_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    networks:
      - typestream_network
    command: sh -c "corepack enable && pnpm install --frozen-lockfile --force && pnpm dev --host 0.0.0.0 --port 5173"
    depends_on:
      - envoy
    environment:
      - VITE_SERVER_URL=http://localhost:8080
      - NODE_OPTIONS=--max-old-space-size=4096
