Output type-checking.gif

Set Theme "Monokai Pro"
Set FontSize 22
Set Width 1300
Set Height 650

Type typestream

Enter

Type ' cat /dev/kafka/local/topics/books | cut .name'

Enter

Sleep 2s

Type 'file /dev/kafka/local/topics/books'

Enter

Sleep 2s

Type ' cat /dev/kafka/local/topics/books | cut .title'

Enter

Sleep 2s

Ctrl+C

Type exit

Enter

Type "# Safer pipelines with TypeStream 🎉"

Enter

Sleep 2s
