// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.32.1
// source: job.proto

package job_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JobServiceClient is the client API for JobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobServiceClient interface {
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
	CreateJobFromGraph(ctx context.Context, in *CreateJobFromGraphRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	CreatePreviewJob(ctx context.Context, in *CreatePreviewJobRequest, opts ...grpc.CallOption) (*CreatePreviewJobResponse, error)
	StopPreviewJob(ctx context.Context, in *StopPreviewJobRequest, opts ...grpc.CallOption) (*StopPreviewJobResponse, error)
	StreamPreview(ctx context.Context, in *StreamPreviewRequest, opts ...grpc.CallOption) (JobService_StreamPreviewClient, error)
	InferGraphSchemas(ctx context.Context, in *InferGraphSchemasRequest, opts ...grpc.CallOption) (*InferGraphSchemasResponse, error)
	ListOpenAIModels(ctx context.Context, in *ListOpenAIModelsRequest, opts ...grpc.CallOption) (*ListOpenAIModelsResponse, error)
}

type jobServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobServiceClient(cc grpc.ClientConnInterface) JobServiceClient {
	return &jobServiceClient{cc}
}

func (c *jobServiceClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	out := new(CreateJobResponse)
	err := c.cc.Invoke(ctx, "/io.typestream.grpc.JobService/CreateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) CreateJobFromGraph(ctx context.Context, in *CreateJobFromGraphRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	out := new(CreateJobResponse)
	err := c.cc.Invoke(ctx, "/io.typestream.grpc.JobService/CreateJobFromGraph", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, "/io.typestream.grpc.JobService/ListJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) CreatePreviewJob(ctx context.Context, in *CreatePreviewJobRequest, opts ...grpc.CallOption) (*CreatePreviewJobResponse, error) {
	out := new(CreatePreviewJobResponse)
	err := c.cc.Invoke(ctx, "/io.typestream.grpc.JobService/CreatePreviewJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) StopPreviewJob(ctx context.Context, in *StopPreviewJobRequest, opts ...grpc.CallOption) (*StopPreviewJobResponse, error) {
	out := new(StopPreviewJobResponse)
	err := c.cc.Invoke(ctx, "/io.typestream.grpc.JobService/StopPreviewJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) StreamPreview(ctx context.Context, in *StreamPreviewRequest, opts ...grpc.CallOption) (JobService_StreamPreviewClient, error) {
	stream, err := c.cc.NewStream(ctx, &JobService_ServiceDesc.Streams[0], "/io.typestream.grpc.JobService/StreamPreview", opts...)
	if err != nil {
		return nil, err
	}
	x := &jobServiceStreamPreviewClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type JobService_StreamPreviewClient interface {
	Recv() (*StreamPreviewResponse, error)
	grpc.ClientStream
}

type jobServiceStreamPreviewClient struct {
	grpc.ClientStream
}

func (x *jobServiceStreamPreviewClient) Recv() (*StreamPreviewResponse, error) {
	m := new(StreamPreviewResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jobServiceClient) InferGraphSchemas(ctx context.Context, in *InferGraphSchemasRequest, opts ...grpc.CallOption) (*InferGraphSchemasResponse, error) {
	out := new(InferGraphSchemasResponse)
	err := c.cc.Invoke(ctx, "/io.typestream.grpc.JobService/InferGraphSchemas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) ListOpenAIModels(ctx context.Context, in *ListOpenAIModelsRequest, opts ...grpc.CallOption) (*ListOpenAIModelsResponse, error) {
	out := new(ListOpenAIModelsResponse)
	err := c.cc.Invoke(ctx, "/io.typestream.grpc.JobService/ListOpenAIModels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServiceServer is the server API for JobService service.
// All implementations must embed UnimplementedJobServiceServer
// for forward compatibility
type JobServiceServer interface {
	CreateJob(context.Context, *CreateJobRequest) (*CreateJobResponse, error)
	CreateJobFromGraph(context.Context, *CreateJobFromGraphRequest) (*CreateJobResponse, error)
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	CreatePreviewJob(context.Context, *CreatePreviewJobRequest) (*CreatePreviewJobResponse, error)
	StopPreviewJob(context.Context, *StopPreviewJobRequest) (*StopPreviewJobResponse, error)
	StreamPreview(*StreamPreviewRequest, JobService_StreamPreviewServer) error
	InferGraphSchemas(context.Context, *InferGraphSchemasRequest) (*InferGraphSchemasResponse, error)
	ListOpenAIModels(context.Context, *ListOpenAIModelsRequest) (*ListOpenAIModelsResponse, error)
	mustEmbedUnimplementedJobServiceServer()
}

// UnimplementedJobServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJobServiceServer struct {
}

func (UnimplementedJobServiceServer) CreateJob(context.Context, *CreateJobRequest) (*CreateJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJob not implemented")
}
func (UnimplementedJobServiceServer) CreateJobFromGraph(context.Context, *CreateJobFromGraphRequest) (*CreateJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJobFromGraph not implemented")
}
func (UnimplementedJobServiceServer) ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedJobServiceServer) CreatePreviewJob(context.Context, *CreatePreviewJobRequest) (*CreatePreviewJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePreviewJob not implemented")
}
func (UnimplementedJobServiceServer) StopPreviewJob(context.Context, *StopPreviewJobRequest) (*StopPreviewJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopPreviewJob not implemented")
}
func (UnimplementedJobServiceServer) StreamPreview(*StreamPreviewRequest, JobService_StreamPreviewServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPreview not implemented")
}
func (UnimplementedJobServiceServer) InferGraphSchemas(context.Context, *InferGraphSchemasRequest) (*InferGraphSchemasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InferGraphSchemas not implemented")
}
func (UnimplementedJobServiceServer) ListOpenAIModels(context.Context, *ListOpenAIModelsRequest) (*ListOpenAIModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOpenAIModels not implemented")
}
func (UnimplementedJobServiceServer) mustEmbedUnimplementedJobServiceServer() {}

// UnsafeJobServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobServiceServer will
// result in compilation errors.
type UnsafeJobServiceServer interface {
	mustEmbedUnimplementedJobServiceServer()
}

func RegisterJobServiceServer(s grpc.ServiceRegistrar, srv JobServiceServer) {
	s.RegisterService(&JobService_ServiceDesc, srv)
}

func _JobService_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.typestream.grpc.JobService/CreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_CreateJobFromGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobFromGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).CreateJobFromGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.typestream.grpc.JobService/CreateJobFromGraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).CreateJobFromGraph(ctx, req.(*CreateJobFromGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.typestream.grpc.JobService/ListJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_CreatePreviewJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePreviewJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).CreatePreviewJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.typestream.grpc.JobService/CreatePreviewJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).CreatePreviewJob(ctx, req.(*CreatePreviewJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_StopPreviewJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopPreviewJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).StopPreviewJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.typestream.grpc.JobService/StopPreviewJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).StopPreviewJob(ctx, req.(*StopPreviewJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_StreamPreview_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPreviewRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobServiceServer).StreamPreview(m, &jobServiceStreamPreviewServer{stream})
}

type JobService_StreamPreviewServer interface {
	Send(*StreamPreviewResponse) error
	grpc.ServerStream
}

type jobServiceStreamPreviewServer struct {
	grpc.ServerStream
}

func (x *jobServiceStreamPreviewServer) Send(m *StreamPreviewResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _JobService_InferGraphSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferGraphSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).InferGraphSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.typestream.grpc.JobService/InferGraphSchemas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).InferGraphSchemas(ctx, req.(*InferGraphSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_ListOpenAIModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOpenAIModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).ListOpenAIModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.typestream.grpc.JobService/ListOpenAIModels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).ListOpenAIModels(ctx, req.(*ListOpenAIModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobService_ServiceDesc is the grpc.ServiceDesc for JobService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.typestream.grpc.JobService",
	HandlerType: (*JobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJob",
			Handler:    _JobService_CreateJob_Handler,
		},
		{
			MethodName: "CreateJobFromGraph",
			Handler:    _JobService_CreateJobFromGraph_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _JobService_ListJobs_Handler,
		},
		{
			MethodName: "CreatePreviewJob",
			Handler:    _JobService_CreatePreviewJob_Handler,
		},
		{
			MethodName: "StopPreviewJob",
			Handler:    _JobService_StopPreviewJob_Handler,
		},
		{
			MethodName: "InferGraphSchemas",
			Handler:    _JobService_InferGraphSchemas_Handler,
		},
		{
			MethodName: "ListOpenAIModels",
			Handler:    _JobService_ListOpenAIModels_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPreview",
			Handler:       _JobService_StreamPreview_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "job.proto",
}
